GRANT CONNECT,RESOURCE,UNLIMITED TABLESPACE TO PCROOM IDENTIFIED BY PCROOM;
ALTER USER PCROOM DEFAULT TABLESPACE USERS;
ALTER USER PCROOM TEMPORARY TABLESPACE TEMP;
CONNECT PCROOM/PCROOM
  

  CREATE TABLE "PCROOM"."CUSTOMER" 
   (	"ID" VARCHAR2(30) NOT NULL ENABLE, 
	"ROLE" VARCHAR2(10) NOT NULL ENABLE, 
	"JOIN_DATE" DATE NOT NULL ENABLE, 
	"REMAIN_TIME" NUMBER(*,0) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(20), 
	"PHONE" VARCHAR2(20), 
	"NAME" VARCHAR2(30), 
	"BIRTHDAY" DATE, 
	"ADDRESS" VARCHAR2(100), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 


  CREATE TABLE "PCROOM"."PRODUCT" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"PRICE" NUMBER(*,0) NOT NULL ENABLE, 
	"KINDS" VARCHAR2(30) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 


  CREATE TABLE "PCROOM"."BUYTIME" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"PLAN_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"CUSTOMER_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"PAYMENT_DATE" DATE NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 FOREIGN KEY ("PLAN_ID")
	  REFERENCES "PCROOM"."RATEPLAN" ("ID") ENABLE, 
	 FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "PCROOM"."CUSTOMER" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 


  CREATE TABLE "PCROOM"."SEAT" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"IS_USABLE" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE, 
	"CUSTOMER_ID" VARCHAR2(30), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "PCROOM"."CUSTOMER" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 


  CREATE TABLE "PCROOM"."RATEPLAN" 
   (	"ID" VARCHAR2(30) NOT NULL ENABLE, 
	"APPLY_TIME" NUMBER(*,0) NOT NULL ENABLE, 
	"PRICE" NUMBER(*,0) NOT NULL ENABLE, 
	"ROLE" VARCHAR2(10) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 


  CREATE TABLE "PCROOM"."VISIT" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"CUSTOMER_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"SEAT_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"VISIT_DATE" DATE, 
	"EXIT_DATE" DATE, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "PCROOM"."CUSTOMER" ("ID") ENABLE, 
	 FOREIGN KEY ("SEAT_ID")
	  REFERENCES "PCROOM"."SEAT" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  
  CREATE TABLE "PCROOM"."PORDER" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"CUSTOMER_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"PAYMENT_WAY" VARCHAR2(10) NOT NULL ENABLE, 
	"PAYMENT_STATUS" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE, 
	"REQUEST" VARCHAR2(100), 
	"PAYMENT_DATE" DATE NOT NULL ENABLE, 
	"SEAT_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"PRICE_SUM" NUMBER(*,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "PCROOM"."CUSTOMER" ("ID") ENABLE, 
	 FOREIGN KEY ("SEAT_ID")
	  REFERENCES "PCROOM"."SEAT" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 


  CREATE TABLE "PCROOM"."PORDER_DETAIL" 
   (	"PORDER_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"PRODUCT_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"NUM" NUMBER(*,0) DEFAULT 1 NOT NULL ENABLE, 
	"PRICE" NUMBER(*,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(30) NOT NULL ENABLE, 
	 CONSTRAINT "PK" PRIMARY KEY ("PORDER_ID", "PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 FOREIGN KEY ("PORDER_ID")
	  REFERENCES "PCROOM"."PORDER" ("ID") ENABLE, 
	 FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "PCROOM"."PRODUCT" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

---------------------------------------------
CREATE SEQUENCE buytime_sequence

START with 1

INCREMENT BY 1;



CREATE OR REPLACE TRIGGER buytime_auto_id_trigger

BEFORE INSERT

ON buytime

REFERENCING NEW AS NEW

FOR EACH ROW

BEGIN

SELECT buytime_SEQUENCE.NEXTVAL INTO :new.id FROM dual;

END;
---------------------------------------------


---------------------------------------------
-- 결제 프로시저 --
create or replace procedure Buy_rateplan_proc(
    p_customerid in varchar2,
    p_applytime in int,
    p_rateplanid in varchar2
)
is

begin

update customer 
set remain_time = (remain_time + p_applytime)
where id=p_customerid;

insert into buytime(plan_id, customer_id, payment_date)
values(p_rateplanid, p_customerid, sysdate);


commit;

end;
---------------------------------------------


---------------------------------------------
CREATE SEQUENCE visit_sequence

START with 1

INCREMENT BY 1;



CREATE OR REPLACE TRIGGER visit_auto_id_trigger

BEFORE INSERT

ON visit

REFERENCING NEW AS NEW

FOR EACH ROW

BEGIN

SELECT visit_SEQUENCE.NEXTVAL INTO :new.id FROM dual;

END;
---------------------------------------------


---------------------------------------------
CREATE SEQUENCE buytime_sequence

START with 1

INCREMENT BY 1;



CREATE OR REPLACE TRIGGER buytime_auto_id_trigger

BEFORE INSERT

ON buytime

REFERENCING NEW AS NEW

FOR EACH ROW

BEGIN

SELECT buytime_SEQUENCE.NEXTVAL INTO :new.id FROM dual;
END;
---------------------------------------------

---------------------------------------------
CREATE SEQUENCE product_sequence

START with 1

INCREMENT BY 1;



CREATE OR REPLACE TRIGGER product_auto_id_trigger

BEFORE INSERT

ON product

REFERENCING NEW AS NEW

FOR EACH ROW

BEGIN

SELECT product_SEQUENCE.NEXTVAL INTO :new.id FROM dual;

END;
---------------------------------------------


---------------------------------------------

CREATE SEQUENCE porder_sequence

START with 1

INCREMENT BY 1;



CREATE OR REPLACE TRIGGER porder_auto_id_trigger

BEFORE INSERT

ON porder

REFERENCING NEW AS NEW

FOR EACH ROW

BEGIN

SELECT porder_SEQUENCE.NEXTVAL INTO :new.id FROM dual;

END;
---------------------------------------------


insert into RATEPLAN values ('회원 1시간 요금제',60,1000,'회원');
insert into RATEPLAN values ('회원 2시간 요금제',120,2000,'회원');
insert into RATEPLAN values ('회원 3시간 요금제',180,3000,'회원');
insert into RATEPLAN values ('회원 6시간 요금제',3600,5000,'회원');
commit;

insert into PRODUCT(name, price, kinds) values ('콜라',1000,'음료');
insert into PRODUCT(name, price, kinds) values ('환타',1000,'음료');
insert into PRODUCT(name, price, kinds) values ('마운틴듀',1000,'음료');
insert into PRODUCT(name, price, kinds) values ('사이다',1000,'음료');
insert into PRODUCT(name, price, kinds) values ('신라면',2000,'라면');
insert into PRODUCT(name, price, kinds) values ('진라면',2000,'라면');
insert into PRODUCT(name, price, kinds) values ('불닭볶음면',2000,'라면');
insert into PRODUCT(name, price, kinds) values ('딜러핫치킨마요볶음면',3000,'라면');
insert into PRODUCT(name, price, kinds) values ('김치볶음밥',3500,'식사류');
insert into PRODUCT(name, price, kinds) values ('치킨마요덮밥',4500,'식사류');
insert into PRODUCT(name, price, kinds) values ('불닭마요덮밥',4500,'식사류');
insert into PRODUCT(name, price, kinds) values ('신라면+콜라',2800,'세트메뉴');
insert into PRODUCT(name, price, kinds) values ('진라면+콜라',2800,'세트메뉴');
insert into PRODUCT(name, price, kinds) values ('김치볶음밥+콜라',4200,'세트메뉴');
insert into PRODUCT(name, price, kinds) values ('치킨마요덮밥+콜라',5000,'세트메뉴');
commit ;

insert into SEAT values (1,'Y',null);
insert into SEAT values (2,'Y',null);
insert into SEAT values (3,'Y',null);
insert into SEAT values (4,'Y',null);
insert into SEAT values (5,'Y',null);
insert into SEAT values (6,'Y',null);
commit;


